In [1]:
import array as ar
arr1 = ar.array ('i', [100, 23, 189, 3456])
arr1[0], arr1[3]

(100, 3456)

In [1]:
import sys
sp1=[1,2,3,4]
print(sp1)
print(sys.getsizeof(sp1))

[1, 2, 3, 4]
96


In [71]:
import array as ar
import timeit
ar1=ar.array('i', [1,2,3,4])
ar2=ar.array('i', [5,6,7])
ar3=ar.array('i',[8,9,10,13,12])
ar4=ar.array('i',[8,5])
ar5=ar.array('i',[12,4,6,3,9,10,23])
sp5=[12,4,6,3,9,10,23]
sp4=[8,5]
sp3=[8,9,10,13,12]
sp2=[5,6,7]
sp1=[1,2,3,4]

a=timeit.default_timer()
ar1.count(2)
len(ar1)
print('время на измерение длины массива из 4 элементов', timeit.default_timer()-a)
a=timeit.default_timer()
sp1.count(2)
len(sp1)
print('время на измерение длины массива из 4 элементов', timeit.default_timer()-a)
print('**************************************************************************')

a=timeit.default_timer()
ar2.remove(5)
len(ar2)
print('время на измерение длины массива из 3 элементов', timeit.default_timer()-a)
a=timeit.default_timer()
sp2.remove(5)
len(sp2)
print('время на измерение длины массива из 3 элементов', timeit.default_timer()-a)
print('**************************************************************************')

a=timeit.default_timer()
ar3.pop(0)
len(ar3)
print('время на измерение длины массива из 5 элементов', timeit.default_timer()-a)
a=timeit.default_timer()
sp3.pop(0)
len(sp3)
print('время на измерение длины массива из 5 элементов', timeit.default_timer()-a)
print('**************************************************************************')

a=timeit.default_timer()
ar4.reverse()
len(ar4)
print('время на измерение длины массива из 2 элементов', timeit.default_timer()-a)
a=timeit.default_timer()
len(sp4)
sp4.reverse()
print('время на измерение длины массива из 2 элементов', timeit.default_timer()-a)
print('**************************************************************************')

a=timeit.default_timer()
ar5.count(3)
len(ar5)
print('время на измерение длины массива из 7 элементов', timeit.default_timer()-a)
a=timeit.default_timer()
sp5.count(3)
len(sp5)
print('время на измерение длины массива из 7 элементов', timeit.default_timer()-a)
print('**************************************************************************')

время на измерение длины массива из 4 элементов 0.0002379930001552566
время на измерение длины массива из 4 элементов 0.00019261499983258545
**************************************************************************
время на измерение длины массива из 3 элементов 0.00018170400016970234
время на измерение длины массива из 3 элементов 0.00016536400016775588
**************************************************************************
время на измерение длины массива из 5 элементов 0.0001696760000413633
время на измерение длины массива из 5 элементов 0.0001984180003091751
**************************************************************************
время на измерение длины массива из 2 элементов 0.00017100900004152209
время на измерение длины массива из 2 элементов 0.0002369950002503174
**************************************************************************
время на измерение длины массива из 7 элементов 0.0002032570000665146
время на измерение длины массива из 7 элементов 0.0001703580001048

задача 1
В массиве, содержащем положительные и отрицательные целые числа, вычислить сумму четных положительных элементов.

In [2]:
import array as ar
import timeit
ar1 = ar.array ('i',[1,2,-4,3,-3,-2,5,6,-8,7])
summa = 0
for i in ar1:
    if i>0 and (i%2)==0:
        summa += i

        
print(summa)
a=timeit.default_timer()
len(ar1)
print('время на измерение длины массива ', timeit.default_timer()-a)

8
время на измерение длины массива  0.00012865599995848243


Задача 2:
В массиве найти максимальный элемент с четным индексом.
Другая формулировка задачи: среди элементов массива с четными индексами, найти тот,
который имеет максимальное значение.

In [4]:
import array as ar
import timeit
ar2 = ar.array ('i',[1,3,2,5,6,3,8,10])
maxx = 0
for i in range(0,len(ar2)):
    if i%2==0:
        if maxx<ar2[i]:
            maxx = ar2[i]
            
print(maxx)
a=timeit.default_timer()
len(ar2)
print('время на измерение длины массива ', timeit.default_timer()-a)

8
время на измерение длины массива  0.00011519199995291274


Задача 3:
Выполните oбработку элементов прямоугольной матрицы A, имеющей N строк и M столбцов. Все
элeменты имeют целый тип. Дано целое число H. Опрeделите, какие столбцы имeют хотя бы
однo такое число, а какие не имeют.

In [5]:
import numpy as num
import timeit
ar3 = num.array ([[1,1,2,3,2], [1,2,2,3,4]])
h = 2
rez = []
for i in ar3:
    for j in range(0,len(i)):
        if i[j]==h:
            if j+1 not in rez:
                rez.append(j+1)
            
print (ar3)
print('Столбцы '+str(rez)+' имеют число '+str(h)+' хотя бы один раз')
a=timeit.default_timer()
len(ar3)
print('время на измерение длины массива ', timeit.default_timer()-a)

[[1 1 2 3 2]
 [1 2 2 3 4]]
Столбцы [3, 5, 2] имеют число 2 хотя бы один раз
время на измерение длины массива  5.0555000029817165e-05


Задача 4:
Найти в массиве те элементы, значение которых меньше среднего арифметического, взятого от всех элементов массива.

In [6]:
import array as ar
import timeit
ar4 = ar.array ('i',[1,2,3,4,5,2,4])
sr = sum(ar4)/len(ar4)
n = []
for i in ar4:
    if i<sr:
        n.append(i)
        
print(n)
a=timeit.default_timer()
len(ar4)
print('время на измерение длины массива ', timeit.default_timer()-a)

[1, 2, 2]
время на измерение длины массива  8.025499994346319e-05


Задача 5:
В одномерном массиве целых чисел определить два наименьших элемента. Они могут быть как равны между собой (оба являться минимальными), так и различаться.

In [10]:
import array as ar
import timeit
min1 = 0
min2 = 0
arr5 = ar.array ('i', [100, 23, 189, 4])

min1 = min(arr5)
arr5.remove(min1)
min2 = min(arr5)
print(min1,min2)

a=timeit.default_timer()
len(arr5)
print('время на измерение длины массива ', timeit.default_timer()-a)

4 23
время на измерение длины массива  7.773000004362984e-05


Задача 6:
Сжать массив, удалив из него все элементы, величина которых находится в интервале [а, b].
Освободившиеся в конце массива элементы заполнить нулями.

In [26]:
import array as ar
import timeit
a = 2
b = 9
ar6 = ar.array ('i', [10, 20, 43, 2])
s = 0
while s<len(ar6):
    if a<=ar6[s]<=b:
        ar6.pop(s)
        ar6.append(0)
    else:
        s+=1
print(ar6.tolist())
a=timeit.default_timer()
len(ar6)
print('время на измерение длины массива ', timeit.default_timer()-a)


[10, 20, 43, 0]
время на измерение длины массива  7.735999997748877e-05


Задача 7:
Вычислить сумму модулей элементов массива, расположенных после первого отрицательного
элемента.
Например, в массиве [5, 3, -1, 8, 0, -6, 1] первый отрицательный элемент является третьим
по счету, а сумма модулей стоящих после него элементов массива будет составлять 8 + 0 + 6
+ 1 = 15.

In [33]:
import array as ar
import timeit
ar7 = ar.array ('i', [10, 0, -2 , 1,-3,3,1]) 
n= -1
for i in range(0,len(ar7)):
    if ar7[i] < 0:
        n = i
        break

if n == -1:
    print('Таких чисел нет')
else:
    a = 0
    for i in range(n+1,len(ar7)):
        a += abs(ar7[i])
    print('Сумма модулей элементов массива: ', a)
    
a=timeit.default_timer()
len(ar7)
print('время на измерение длины массива ', timeit.default_timer()-a)

Сумма модулей элементов массива:  8
время на измерение длины массива  7.547400014118466e-05


Задача 8:
Пользователь вводит упорядоченный список/массив книг (заданной длины по алфавиту).
Добавить новую книгу, сохранив упорядоченность списка по алфавиту

In [39]:
import numpy as num
import timeit
al = num.array (['Оно','Гордость и предубеждение']) 
al = sorted(al)
x = input('Введите название книги: ')
al.append(x)
print(sorted(al))
a=timeit.default_timer()
len(al)
print('время на измерение длины массива ', timeit.default_timer()-a)

Введите название книги: Тихий дон
['Гордость и предубеждение', 'Оно', 'Тихий дон']
время на измерение длины массива  9.47700000324403e-05


In [138]:
import numpy as num
import timeit
al = num.array (['Оно','Гордость и предубеждение']) 
al.insert('книга',1)
al.pop(2)
for i in al:
    print(i)

AttributeError: 'numpy.ndarray' object has no attribute 'insert'

Задача 9:
Дан список/массив целых чисел. Упорядочьте по возрастанию только:
а) положительные числа;
б) элементы с четными порядковыми номерами в списке.

In [145]:
# A
import array as ar
import timeit
ar8 = ar.array ('i', [[10,12,13], 0, -2 , 1,-3,3,1]) 
new=[]
for i in ar8:
    if i > 0:
        new.append(i)
print(sorted(new))
a=timeit.default_timer()
len(ar8)
print('время на измерение длины массива ', timeit.default_timer()-a)

for u in ar8:
    print(u)

TypeError: an integer is required (got type list)

In [46]:
# B
import array as ar
import timeit
ar9 = ar.array ('i', [10, 0, -2 , 1,-3,3,1]) 
new=[]
for i in range(0, len(ar9)):
    if (i%2) == 0:
        new.append(ar9[i])
print(sorted(new))
a=timeit.default_timer()
len(ar9)
print('время на измерение длины массива ', timeit.default_timer()-a)

[-3, -2, 1, 10]
время на измерение длины массива  9.803500006455579e-05


Задача 10:
Даны два списка/массива. Определите, совпадают ли множества их элементов.

In [51]:
import array as ar
import timeit
s=ar.array('i',[1,5,3])
b=ar.array('i',[3,5,1])
if set(s)==set(b):
    print("Совпадает")
else:
    print("Не совпадает")
a=timeit.default_timer()
len(s)
print('время на измерение длины массива ', timeit.default_timer()-a) 
a=timeit.default_timer()
len(b)
print('время на измерение длины массива ', timeit.default_timer()-a)  

Совпадает
время на измерение длины массива  0.00017824499991547782
время на измерение длины массива  0.0001222149999193789


Задача 11:
Дан список/массив. После каждого элемента добавьте предшествующую ему часть списка.

In [56]:
import array as ar
import timeit
s=ar.array('i',[1,5,3,4,2])
new=[]
for i in range(0,len(s)):
    for j in range(0,i):
        new.append(s[j])
        
print(new)
a=timeit.default_timer()
len(s)
print('время на измерение длины массива ', timeit.default_timer()-a) 

[1, 1, 5, 1, 5, 3, 1, 5, 3, 4]
время на измерение длины массива  0.00015961300005074008


Задача 12
Пусть элементы списка/массива хранят символы предложения. Замените каждое вхождение слова
"itmathrepetitor" на "silence".

In [58]:
# массив
import numpy as num
import timeit
s=num.array(['hello','itmathrepetitor','world'])
for m, n in enumerate(s):
    if n=='itmathrepetitor':
        s[m]="silence"
print(' '.join(s))
        


a=timeit.default_timer()
len(s)
print('время на измерение длины массива ', timeit.default_timer()-a) 

hello silence world
время на измерение длины массива  0.0001359349998892867


In [113]:
# список
import timeit
s = ['hello','itmathrepetitor','world']
for m, n in enumerate(s):
    if n=='itmathrepetitor':
        s[m]="silence"
print(' '.join(s))
a=timeit.default_timer()
len(s)
print('время на измерение длины списка ', timeit.default_timer()-a) 

hello silence world
время на измерение длины списка  0.00019762200008699438


Задача 13*:
Дан текстовый файл. Создайте двусвязный список (или массив), каждый элемент которого содержит количество символов в соответствующей строке текста.

In [68]:
# список
import timeit
ar1 = []
f = open("text.txt", "r")
for line in f:
    ar1.append(len(line))

print(ar1)
a=timeit.default_timer()
len(ar1)
print('время на измерение длины списка ', timeit.default_timer()-a) 

[43, 11, 31]
время на измерение длины списка  0.0001770230001056916


In [116]:
# массив
import array as ar
import timeit
f = open("text.txt", "r")
ar1 =ar.array('i',[])
for line in f:
    ar1.append(len(line))

print(ar1)
a=timeit.default_timer()
len(ar1)
print('время на измерение длины массива ', timeit.default_timer()-a) 

array('i', [43, 11, 31])
время на измерение длины массива  0.0001732239998091245


Задача 14*:
Создайте двусвязный список (или массив) групп факультета. Каждая группа представляет собой односвязный список (или массив) студентов.

In [75]:
import numpy as num
s = num.array([['Сэрт','Гусаров','Молитвин'],['Лазарева','Миронов','Цуприк']])
print(s)
a=timeit.default_timer()
len(s)
print('время на измерение длины массива ', timeit.default_timer()-a) 

[['Сэрт' 'Гусаров' 'Молитвин']
 ['Лазарева' 'Миронов' 'Цуприк']]
время на измерение длины массива  0.0001969609998013766


In [117]:
s = [['Сэрт','Гусаров','Молитвин'],['Лазарева','Миронов','Цуприк']]
print(s)
a=timeit.default_timer()
len(s)
print('время на измерение длины списка ', timeit.default_timer()-a) 

[['Сэрт', 'Гусаров', 'Молитвин'], ['Лазарева', 'Миронов', 'Цуприк']]
время на измерение длины списка  0.00012180500016256701


Задача 15*:
Дан список студентов. Элемент списка содержит фамилию, имя, отчество, год рождения, курс,
номер группы, оценки по пяти предметам. 
1. Упорядочите студентов по курсу, причем студенты одного курса располагались в алфавитном порядке.
2. Найдите средний балл каждой группы по каждому предмету. 
3. Определите самого старшего студента и самого младшего студентов.
4. Для каждой группы найдите лучшего с точки зрения успеваемости студента. 
Выберете структуру данных для программной реализации.

In [120]:
import numpy as num
import timeit
k = num.array([['Сэрт Анна Вадимовна', 2003, '1','ПИ19-3',5,3,5,5,5],['Лазарева Яна Владимировна', 2001, 1, 'ПИ19-1',5,4,5,5,5],['Хватов Артур Юрьевич',2001,1,'ПИ19-1',5,4,4,4,5],['Теплов Артём Алексеевич', 2000, 1,'ПИ19-3',5,4,4,5,5]])
s = sorted(k, key = lambda x: x[3])
print(s)
print('***средний балл каждой группы по каждому предмету**')
print('***ПИ19-1***')
count = 0
summa = 0
for i in range(1,6):
    for j in s:
        if j[3]=='ПИ19-1':
            count += 1
            n = -6 + i
            summa += int(j[n])
    print('Средний балл по', i, 'предмету группы ПИ19-1 равен', summa/count)
print('***ПИ19-3***')
count = 0
summa = 0
for i in range(1,6):
    for j in s:
        if j[3]=='ПИ19-3':
            count += 1
            n = -6 + i
            summa += int(j[n])
    print('Средний балл по', i, 'предмету группы ПИ19-3 равен', summa/count)
    
maxy= 1000000
miny= -1
for i in s:
    print(int(i[1]))
    if int(i[1])>miny:
        miny = int(i[1])
        chel_min = i
    elif int(i[1])<maxy:
        maxy = int(i[1])
        chel_max = i
        
print('Самый старший ученик',chel_max)
print('Самый младший ученик', chel_min)

print("***Лучший студент***")

print('***ПИ19-1***')
summ = 0
sr = 0
max_sr = 0
for i in s:
    if i[3] == 'ПИ19-1':
        summ = int(i[-5]+i[-4]+i[-3]+i[-2]+i[-1])
        sr = summ/5
        if sr > max_sr:
            max_sr = sr
            chel = i
print('Лучший студент группы ПИ19-1', chel)

print('***ПИ19-3***')
summ = 0
sr = 0
max_sr = 0
for i in s:
    if i[3] == 'ПИ19-3':
        summ = int(i[-5]+i[-4]+i[-3]+i[-2]+i[-1])
        sr = summ/5
        if sr > max_sr:
            max_sr = sr
            chel = i
            
print('Лучший студент группы ПИ19-3', chel)

a=timeit.default_timer()
len(s)
print('время на измерение длины массива', timeit.default_timer()-a) 

[array(['Лазарева Яна Владимировна', '2001', '1', 'ПИ19-1', '5', '4', '5',
       '5', '5'], dtype='<U25'), array(['Хватов Артур Юрьевич', '2001', '1', 'ПИ19-1', '5', '4', '4', '4',
       '5'], dtype='<U25'), array(['Сэрт Анна Вадимовна', '2003', '1', 'ПИ19-3', '5', '3', '5', '5',
       '5'], dtype='<U25'), array(['Теплов Артём Алексеевич', '2000', '1', 'ПИ19-3', '5', '4', '4',
       '5', '5'], dtype='<U25')]
***средний балл каждой группы по каждому предмету**
***ПИ19-1***
Средний балл по 1 предмету группы ПИ19-1 равен 5.0
Средний балл по 2 предмету группы ПИ19-1 равен 4.5
Средний балл по 3 предмету группы ПИ19-1 равен 4.5
Средний балл по 4 предмету группы ПИ19-1 равен 4.5
Средний балл по 5 предмету группы ПИ19-1 равен 4.6
***ПИ19-3***
Средний балл по 1 предмету группы ПИ19-3 равен 5.0
Средний балл по 2 предмету группы ПИ19-3 равен 4.25
Средний балл по 3 предмету группы ПИ19-3 равен 4.333333333333333
Средний балл по 4 предмету группы ПИ19-3 равен 4.5
Средний балл по 5 предмету групп

In [119]:
import timeit
s = [['Сэрт Анна Вадимовна', 2003, '1','ПИ19-3',5,3,5,5,5],['Лазарева Яна Владимировна', 2001, 1, 'ПИ19-1',5,4,5,5,5],['Хватов Артур Юрьевич',2001,1,'ПИ19-1',5,4,4,4,5],['Теплов Артём Алексеевич', 2000, 1,'ПИ19-3',5,4,4,5,5]]
a=timeit.default_timer()
len(s)
print('время на измерение длины списка ', timeit.default_timer()-a) 

время на измерение длины списка  0.00011895500028913375


16* Выполнить программную реализацию калькулятора матриц.

In [111]:
import numpy as num
import timeit
ar1=num.array([[1,2,3],[4,9,2]])
ar2=num.array([[32,6,8],[13,2,9]])
print( ar1)
print('.........')
print( ar2)
for i in range(len(ar1)):
    for k in range(len(ar2)):
        out1=ar1+ar2
        out2=ar1-ar2
        out3=ar1*ar2
print('----------------------')
print('Сумма матриц: ',out1)
print('Разность матриц: ',out2)
print('Произведение матриц: ',out3)
a=timeit.default_timer()
len(ar1)
print('время на измерение длины 1 массива ', timeit.default_timer()-a)
a=timeit.default_timer()
len(ar2)
print('время на измерение длины 2 массива ', timeit.default_timer()-a) 

[[1 2 3]
 [4 9 2]]
.........
[[32  6  8]
 [13  2  9]]
----------------------
Сумма матриц:  [[33  8 11]
 [17 11 11]]
Разность матриц:  [[-31  -4  -5]
 [ -9   7  -7]]
Произведение матриц:  [[32 12 24]
 [52 18 18]]
время на измерение длины 1 массива  0.00019070500002271729
время на измерение длины 2 массива  0.00015048900058900472


In [121]:
import timeit
ar1=[[1,2,3],[4,9,2]]
ar2=[[32,6,8],[13,2,9]]
a=timeit.default_timer()
len(ar1)
print('время на измерение длины 1 списка ', timeit.default_timer()-a)
a=timeit.default_timer()
len(ar2)
print('время на измерение длины 2 списка ', timeit.default_timer()-a) 

время на измерение длины 1 списка  0.000125151999782247
время на измерение длины 2 списка  9.162400056084152e-05


Задача 17:
Сдвинуть элементы массива в указанном направлении (влево или вправо) и на указанное число
шагов. Освободившиеся ячейки заполнить нулями. Выводить массив после каждого шага.

In [129]:
import array as ar
import timeit
s = ar.array('i',[2,-1,3,6,-3,9])
w = int(input('Сдвинуть список 1 - влево/2 - вправо /3 - выход'))
while w is not 3:
    x = int(input('Сколько шагов? '))
    if w == 1:
        for i in range(0,x):
            s.pop(len(s)-1)
        for i in range(0,x):
            s.append(0)
    else:
        for i in range(0,x):
            s.pop(0)
        for i in range(0,x):
            s.insert(0,0)
    print(s)
    w = int(input('Сдвинуть список 1 - влево/2 - вправо /3 - выход '))
a=timeit.default_timer()
len(s)
print('время на измерение длины массива ', timeit.default_timer()-a) 

Сдвинуть список 1 - влево/2 - вправо /3 - выход3
время на измерение длины массива  7.103499956429005e-05


In [128]:
#18 Заполнить массив случайными положительными и отрицательными целыми числами. Вывести его на экран. 
#Удалить из массива все отрицательные элементы и снова вывести.
import array as ar
import timeit
ar1=ar.array('i',[2,-1,3,6,-3,9])
print(ar1)
print('.....................')
s=0
for s in range(len(ar1)):
    if ar1[s]<0:
        ar1.pop(s)
        ar1.append(0)
print(ar1.tolist())
a=timeit.default_timer()
len(ar1)
print('время на измерение длины массива ', timeit.default_timer()-a) 

array('i', [2, -1, 3, 6, -3, 9])
.....................
[2, 3, 6, 9, 0, 0]
время на измерение длины массива  0.00017349199879390653


Задача 19:
Заполнить вводом с клавиатуры численный массив за исключением последнего элемента, вывести его на экран. 
Запросить еще одно значение и его позицию в в массиве. 
Вставить указанное число в заданную позицию, подвинув элементы после него.

In [133]:
import array as ar
import timeit

s = ar.array('i',[])

x = int(input('1 - вставить число / 2 - выход '))

while x is not 2:
    i = int(input('введите число '))
    s.append(i)
    x = int(input('1 - вставить число / 2 - выход'))
    
print('последнее число ',s[-1])
s.pop(len(s)-1)

print(s.tolist())

r = int(input('введите еще число '))
b = int(input('и его индекс '))

s.insert(b,r)
print(s.tolist())
    
a=timeit.default_timer()
len(s)
print('время на измерение длины массива ', timeit.default_timer()-a) 

1 - вставить число / 2 - конец1
введите число 5
1 - вставить число / 2 - конец 3
введите число 2
1 - вставить число / 2 - конец 48
введите число 3
1 - вставить число / 2 - конец 1
введите число 29
1 - вставить число / 2 - конец 2
последнее число  29
[5, 2, 3]
введите еще число 6
и его индекс 2
[5, 2, 6, 3]
время на измерение длины массива  0.00013114600005792454


In [134]:
# 20
from random import random
import array as ar
N = 3
ar1 = [0,0,0]
ar2 = [0,0,0]
ar3 = [0,0,0]
for i in range(N):
    ar1[i] = int(random() * 100)
 
for i in range(N):
    ar2[i] = int(input('Введите числа для второго массива:'))
 
for i in range(N):
    ar3[i] = ar1[i] + ar2[i]
 
print(ar1)
print(ar2)
print(ar3)

Введите числа для второго массива:22
Введите числа для второго массива:3
Введите числа для второго массива:1
[79, 33, 6]
[22, 3, 1]
[101, 36, 7]


Задача 21:
Сгенерировать 2000 случайных целых чисел в диапазоне от -5 до 4, записать их в ячейки
массива. Посчитать сколько среди них положительных, отрицательных и нулевых значений.
Вывести на экран элементы массива и посчитанные количества. Рассмотрите возможность
использования numpy.set_printoptions для полноценного вывода занчений массива на экран.

In [135]:
from random import random
import numpy as num
import array as ar

otr = 0
pol = 0
zero = 0
ar1 =ar.array('i',[])
num.set_printoptions(threshold=2000)
for i in num.arange(2000):
    n = int(random() * 10) - 5
    ar1.append(n)
    print(n, end=' ')
    if n > 0:
        pol += 1
    elif n < 0:
        otr += 1
    else:
        zero += 1 

print("\nПоложительные: ", pol)
print("Отрицательные: ", otr)
print("Нули: ", zero)
a=timeit.default_timer()
len(ar1)
print('время на измерение длины массива ', timeit.default_timer()-a) 
    
    

-3 -2 -2 -3 1 2 3 3 2 -3 -1 0 -2 -1 -1 -2 -2 -1 -5 -1 2 -1 -5 0 0 -2 1 0 0 -3 2 -3 0 0 -3 -3 0 -3 -5 -1 3 4 1 -3 -5 -1 3 3 -2 -4 3 4 4 1 -1 4 2 -1 -5 -2 -2 1 -5 0 -2 -5 -1 -2 3 3 -5 -4 -3 4 0 -1 -1 -2 -2 -5 0 -1 -1 3 -1 -4 0 2 -3 -3 1 -3 -5 3 3 -4 4 2 3 3 -5 -3 -4 4 2 3 3 3 0 -3 4 1 1 1 -5 3 -2 3 4 2 -5 2 -4 0 3 -4 3 -4 1 4 -3 3 0 -5 -2 4 -3 -2 2 -5 -5 -5 2 -4 0 -3 0 4 3 3 2 3 2 -5 -1 2 2 -1 3 4 3 -4 -5 4 -2 1 -5 -5 1 -5 2 3 1 -1 2 -5 -2 3 0 -1 -5 4 4 -4 3 -1 -1 2 4 2 -5 -2 4 2 0 2 3 -4 3 4 2 -2 4 -3 0 2 1 2 -3 -3 0 4 1 -3 1 -4 4 4 -1 0 -3 -1 3 -5 3 -1 -5 -3 1 3 -4 3 -2 0 4 0 -3 3 1 -4 2 -1 -1 3 3 -5 -2 0 -2 2 3 -5 -4 -5 4 1 -3 4 -3 4 -3 3 -5 0 -3 1 2 1 -1 -1 -1 1 1 1 -4 -3 -3 4 -2 0 -4 3 4 4 4 3 -3 -5 0 -4 2 -4 3 -2 1 4 -2 0 2 0 -3 3 3 1 3 -3 -1 -4 -2 -1 0 -3 2 0 -5 0 -2 1 4 4 0 -5 -3 -1 4 1 2 1 -3 0 4 -5 0 -4 -5 -5 -4 4 4 -5 1 -4 3 -4 3 2 -2 0 4 -2 1 3 -2 -2 -4 -3 -5 0 0 0 -1 4 -5 1 4 -5 -2 3 4 -5 -2 -1 2 -4 3 0 -1 1 -1 -4 2 3 -1 -3 -3 4 3 1 -2 -1 4 4 4 0 2 -5 -1 -5 4 -5 3 1 -4 -5 3 