# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html
* Уэс Маккини. Python и анализ данных

In [2]:
import numpy as np

In [2]:
# ar1 = np.random.rand(4,7)
ar1 = [1,2,3,4,5,6]
ar1
[i**2 for i in ar1]

# ar2 = ar1.reshape(4,4)
# ar2

[1, 4, 9, 16, 25, 36]

In [3]:
ar2 = np.array(ar1)
ar2 ** 2

array([ 1,  4,  9, 16, 25, 36])

In [26]:
mask = ar2 < 4

In [27]:
ar2[mask]

array([1, 2, 3])

In [36]:
arr = np.arange(20).reshape(4,5)

arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [58]:
arr = np.random.uniform(0,20,size=(4,7))

In [56]:
# 1
(arr - np.min(arr)) / (np.max(arr)- np.min(arr))

array([[0.95184535, 0.77583074, 0.14651067, 0.85446712, 0.83222382,
        0.7962076 , 0.30453946],
       [0.01362189, 0.27322565, 0.22464052, 0.39077013, 0.96812313,
        0.4093145 , 0.        ],
       [0.09880883, 0.1735541 , 1.        , 0.67067656, 0.47326842,
        0.61738136, 0.80801497],
       [1.        , 0.44015327, 0.36438301, 0.97633573, 1.        ,
        0.30772049, 1.        ]])

In [57]:
#2
(arr - arr.min()) / (arr.max() - arr.min())

array([[0.95184535, 0.77583074, 0.14651067, 0.85446712, 0.83222382,
        0.7962076 , 0.30453946],
       [0.01362189, 0.27322565, 0.22464052, 0.39077013, 0.96812313,
        0.4093145 , 0.        ],
       [0.09880883, 0.1735541 , 1.        , 0.67067656, 0.47326842,
        0.61738136, 0.80801497],
       [1.        , 0.44015327, 0.36438301, 0.97633573, 1.        ,
        0.30772049, 1.        ]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [87]:
arr2 = np.random.uniform(0,10,size=(8,10))
arr2
# arr.max(axis=1)# макс по строкам
b = arr2.sum(axis=1)
b

array([60.35784027, 56.72572822, 43.24586624, 31.99632366, 50.23037831,
       55.47221324, 54.62512452, 52.61319868])

In [89]:
arr2.sum(axis=1)

array([60.35784027, 56.72572822, 43.24586624, 31.99632366, 50.23037831,
       55.47221324, 54.62512452, 52.61319868])

In [90]:
np.max(arr2.sum(axis=1))

60.35784026931591

In [88]:
#ОТВЕТ

msk = arr2.sum(axis=1) == np.max(arr2.sum(axis=1))
arr2[msk]

array([[9.08916021, 9.36001768, 6.19060798, 3.78322334, 9.31240676,
        7.5469568 , 3.74727131, 0.20627405, 1.68270733, 9.4392148 ]])

In [62]:
arr.max(axis=1)# макс по строкам

array([17.69310491, 19.44826134, 19.12971045, 19.09194572])

In [61]:
arr.max(axis=0)# макс по столбцам

array([16.37308794, 19.12971045, 19.44826134, 17.69310491, 12.25830733,
       19.09194572, 14.79716617])

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [97]:
v1 = np.random.randint(0,10,size=(8,))
v2 = np.random.randint(0,10,size=(8,))
v1, v2
a=np.sqrt(np.sum((v1-v2)**2))
a

13.601470508735444

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [117]:
A = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B = np.array([[3, -1], [2, 1]])
C = np.array([[7, 21], [11, 8], [8, 4]])

X = np.linalg.inv(A)@(-C)@(np.linalg.inv(B))
X

array([[ 1.00000000e+00,  1.11022302e-15],
       [-2.00000000e+00,  1.00000000e+00],
       [ 3.00000000e+00, -4.00000000e+00]])

In [ ]:
@ - умножение матрицы на матрицу

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [3]:
file = np.loadtxt('minutes_n_ingredients.csv', dtype = 'int32', delimiter=',', skiprows=1)
print(file[:5])


[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


In [4]:
type(file)

numpy.ndarray

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [29]:
# СР значение
av = np.mean(file, axis=0)[1:]

# Минимум
mn = np.min(file, axis=0)[1:]

# Максимум
mx = np.max(file, axis=0)[1:]

# Медиана
md = np.median(file, axis=0)[1:]

print('Для 2 столбца: ср знач -', av[0], 'минимум - ', mn[0], 'максимум - ', mx[0], 'медиана - ', md[0])
print('Для 3 столбца: ср знач -', av[1], 'минимум - ', mn[1], 'максимум - ', mx[1], 'медиана - ', md[1])

Для 2 столбца: ср знач - 21601.00169 минимум -  0 максимум -  2147483647 медиана -  40.0
Для 3 столбца: ср знач - 9.05528 минимум -  1 максимум -  39 медиана -  9.0


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [3]:
q075 = np.quantile(file[:,1], 0.75)
#  np.quantile(file, 0.75, axis=0)[1]

file1 = file[file[:, 1] < q075]
# file1 = [i for i in file if i[1] < q075] 
# print(file1)
print(file1.size // 3)


73106


In [41]:
print(file1[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [4]:
count = file1[file1==0].size
print('рецепты с 0 в продолжительности -', count)
# file3 = np.copy(file1)


рецепты с 0 в продолжительности - 479


In [5]:
file1 = np.where(file1!=0, file1, 1)
print('Проверка, что значения изменились на 1')
file4 = file1[file1==0].size
print('рецепты с 0 в продолжительности -', file4)

Проверка, что значения изменились на 1
рецепты с 0 в продолжительности - 0


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [6]:
np.unique(file1, axis=0).size

219318

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [7]:
a = np.unique(file1[:,2], axis=0, return_counts=True)
a

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 33, 34],
       dtype=int32),
 array([  12,  778, 2517, 4730, 6589, 7543, 8271, 8294, 7876, 6813, 5637,
        4419, 3204, 2223, 1497,  994,  646,  393,  257,  165,   78,   60,
          30,   27,   25,    7,    5,    4,    7,    3,    1,    1]))

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [8]:
file7 = np.where(file1[:,2]<=5) 
print(file1[file7])

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


In [ ]:
#[i for i in file1 if i[2] <= 5] 

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [9]:
b = file1[:,2]/file1[:,1]
np.mean(b)


0.4863421146749897

In [77]:
np.max(b)

24.0

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [10]:
res = file1[np.argsort(file1[:, 1])][::-1][:100]
res[:6]

array([[265059,     64,     10],
       [200352,     64,     11],
       [141461,     64,     10],
       [ 19615,     64,      3],
       [ 17430,     64,      7],
       [279688,     64,      4]], dtype=int32)

In [80]:
np.mean(res[:,2])

8.84

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [11]:
B = file1[np.random.choice(file1.shape[0], size=10, replace=False), :]
B

array([[288609,     30,     11],
       [ 71552,     35,     11],
       [ 10246,     25,     12],
       [147378,      8,     12],
       [ 57296,      5,      9],
       [ 26654,     45,      4],
       [441875,     18,      8],
       [388869,     60,      9],
       [ 96971,     15,      6],
       [460159,     15,      4]], dtype=int32)

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [12]:
file11 = file1[file1[:, 2] < np.mean(file1, axis = 0)[2]]
(file11.shape[0] / file1.shape[0]) * 100

52.98333926079939

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [26]:
# z = [1 if i[2] <= 5 and i[1] <= 20 else 0 for i in file1] 
cond = (file1[:, 1] <= 20) & (file1[:, 2] <= 5)
z = np.zeros((len(file1), 1), dtype='int32')
file22 = np.copy(file1)
file22 = np.append(file22, z, axis=1)
file22[:,3] = np.where(cond,1,cond)
print(file22)


# z.shape = (73106,1)
# file12 = np.copy(file1)
# file12 = np.append(file12, z, axis=1)
# file12

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [371794     35      8      0]
 [ 43407     35      7      0]
 [370915      5      4      1]]


13. Выведите процент "простых" рецептов в датасете

In [43]:
count= np.where(file1[:,0])
print(file22[cond].size*100 / file22[count].size)

13.065959018411622


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [52]:
# 1 Короткие - менее 10 мин
# 2 Стандартные - 10-20
# 3 Длинные - не менее 20

short = file1[:, 1] < 10
medium = (file1[:, 1] >= 10) & (file1[:, 1] < 20)
long = file1[:, 1] >= 20

In [53]:
file1[short]

array([[ 67660,      5,      6],
       [366174,      7,      9],
       [204134,      5,      3],
       ...,
       [420725,      5,      3],
       [  4747,      1,      9],
       [370915,      5,      4]], dtype=int32)

In [54]:
file1[medium]

array([[ 94746,     10,      6],
       [ 33941,     18,      9],
       [446597,     15,      5],
       ...,
       [ 44120,     17,      5],
       [ 60756,     15,      5],
       [128811,     15,      4]], dtype=int32)

In [55]:
file1[long]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [157911,     60,     14],
       ...,
       [360109,     30,     10],
       [371794,     35,      8],
       [ 43407,     35,      7]], dtype=int32)

In [56]:
file1[short].shape[0]

7588

In [57]:
file1[medium].shape[0]

12661

In [58]:
file1[long].shape[0]

52857

In [59]:
np.concatenate((file1[short], file1[medium], file1[long]), axis=0)

array([[ 67660,      5,      6],
       [366174,      7,      9],
       [204134,      5,      3],
       ...,
       [360109,     30,     10],
       [371794,     35,      8],
       [ 43407,     35,      7]], dtype=int32)

In [61]:
short_m_n_i = file1[short]
short_m_n_i.sort(axis=0)
# short_m_n_i = np.vsplit(short_m_n_i[:,1:], short_m_n_i.shape[0])
short_m_n_i[-1]

array([536728,      9,     29], dtype=int32)

In [62]:
middle_m_n_i = file1[medium][:7588]
middle_m_n_i.sort(axis=0)
# middle_m_n_i = np.vsplit(middle_m_n_i[:,1:], middle_m_n_i.shape[0])
middle_m_n_i[-1]

array([532920,     19,     30], dtype=int32)

In [63]:
long_m_n_i = file1[long][:7588]
long_m_n_i.sort(axis=0)
# long_m_n_i = np.vsplit(long_m_n_i, long_m_n_i .shape[0])
long_m_n_i[-1]

array([537458,     64,     30], dtype=int32)

In [64]:
res = np.stack((short_m_n_i[:,1:], middle_m_n_i[:,1:], long_m_n_i[:,1:]))
res

array([[[ 1,  1],
        [ 1,  1],
        [ 1,  1],
        ...,
        [ 9, 25],
        [ 9, 28],
        [ 9, 29]],

       [[10,  1],
        [10,  1],
        [10,  2],
        ...,
        [19, 25],
        [19, 25],
        [19, 30]],

       [[20,  2],
        [20,  2],
        [20,  2],
        ...,
        [64, 25],
        [64, 25],
        [64, 30]]], dtype=int32)

In [65]:
# Форма массива
res.ndim

3