# Работа с Excel

Материалы:
* Макрушин С.В. Лекция 7: Работа с Excel
* https://docs.xlwings.org/en/stable/quickstart.html
* https://nbviewer.jupyter.org/github/pybokeh/jupyter_notebooks/blob/master/xlwings/Excel_Formatting.ipynb#search_text


## Задачи для совместного разбора

In [1]:
import xlwings as xw
import numpy as np

In [2]:
xw.__version__

'0.19.5'

1. На листе "Рецептура" файла `себестоимостьА_в1.xlsx` для области "Пшеничный хлеб" рассчитать себестоимость всех видов продукции.

In [3]:
wb1 = xw.Book("себестоимостьА_в1.xlsx")
sheet = wb1.sheets["Рецептура"]

In [4]:
consumption = sheet.range("G7:O10").options(np.array).value
consumption

array([[0.2  , 0.4  , 0.02 , 0.02 , 0.01 , 0.005, 0.1  ,   nan,   nan],
       [0.07 , 0.25 , 0.01 , 0.06 , 0.015,   nan, 0.06 , 0.05 ,   nan],
       [0.12 , 0.22 , 0.005,   nan, 0.009, 0.005,   nan, 0.05 , 0.03 ],
       [0.12 , 0.23 , 0.01 ,   nan, 0.015,   nan,   nan,   nan, 0.05 ]])

In [5]:
unit_price = sheet.range("G14:O14").options(np.array).value
unit_price

array([  7.,  10., 184.,  19.,   7., 290., 105.,  83., 260.])

In [6]:
cost_price = np.nan_to_num(consumption * unit_price).sum(axis=1)
cost_price

array([21.48 , 16.525, 17.423, 18.085])

2. Результаты расчетов 1.1 сохранить в отдельном столбце области "Пшеничный хлеб"

In [7]:
sheet.range("T7:T10").options(transpose=True).value = cost_price
sheet.range("T6").value = "Себестоимость"

3. Приблизить форматирование столбца, добавленного в задаче 2 к оформлению всей области.

In [8]:
sheet.range("T4:T6").api.merge()
sheet.range("T4:T6").color = (255,255,0)

4. Выполнить 3 с помощью "протягиваемых" формул.

In [9]:
from xlwings.constants import AutoFillType

In [10]:
sheet.range("U7").formula = "=SUMPRODUCT(G7:O7, $G$14:$O$14)"
sheet.range("U7").api.autofill(destination=sheet.range("U7:U10").api , type=AutoFillType.xlFillDefault)

## Лабораторная работа 7

1. Загрузите данные из файлов `reviews_sample.csv` (__ЛР2__) и `recipes_sample_with_tags_ingredients.csv` (__ЛР5__) в виде `pd.DataFrame`. Обратите внимание на корректное считывание столбца(ов) с индексами. Оставьте в таблице с рецептами следующие столбцы: `id`, `name`, `minutes`, `submitted`, `description`, `n_ingredients`

In [11]:
import pandas as pd

In [12]:
reviews_sample = pd.read_csv("../02_pandas/data/reviews_sample.csv", sep=",", parse_dates=['date'])
reviews_sample = reviews_sample.rename(columns={"Unnamed: 0": "index"})
reviews_sample = reviews_sample.set_index("index")
reviews_sample

user_id  recipe_id       date  rating  \
index                                               
370476        21752      57993 2003-05-01       5   
624300       431813     142201 2007-09-16       5   
187037       400708     252013 2008-01-10       4   
706134   2001852463     404716 2017-12-11       5   
312179        95810     129396 2008-03-14       5   
...             ...        ...        ...     ...   
1013457     1270706     335534 2009-05-17       4   
158736      2282344       8701 2012-06-03       0   
1059834      689540     222001 2008-04-08       5   
453285   2000242659     354979 2015-06-02       5   
691207       463435     415599 2010-09-30       5   

                                                    review  
index                                                       
370476   Last week whole sides of frozen salmon fillet ...  
624300   So simple and so tasty!  I used a yellow capsi...  
187037   Very nice breakfast HH, easy to make and yummy...  
706134   These are a favorite for the holidays and so e...  
312179   Excellent soup!  The tomato flavor is just gre...  
...                                                    ...  
1013457  This recipe was great! I made it last night. I...  
158736   This recipe is outstanding. I followed the rec...  
1059834  Well, we were not a crowd but it was a fabulou...  
453285   I have been a steak eater and dedicated BBQ gr...  
691207   Wonderful and simple to prepare seasoning blen...  

[126696 rows x 5 columns]

In [13]:
recipes_sample_wt = pd.read_csv('../05_data_files/recipes_sample_with_tags_ingredients.csv', sep=",", parse_dates=['submitted'])
recipes_sample_wt = recipes_sample_wt.rename(columns={"Unnamed: 0": "index"})
recipes_sample_wt = recipes_sample_wt.set_index("index")
recipes_sample_wt

id                                               name  minutes  \
index                                                                       
0       84797           love is in the air  beef fondue   sauces       25   
1      107229                               open sesame  noodles       28   
2       95926                         say what   banana sandwich        5   
3      453467                 1 in canada chocolate chip cookies       45   
4      306168                             412 broccoli casserole       40   
...       ...                                                ...      ...   
18805   74023                         zucchini cheddar casserole       50   
18806  415406  zucchini  courgette soup  good for weight watc...       45   
18807  464576                                     zuppa by luisa       70   
18808  267661       zurie s holey rustic olive and cheddar bread       80   
18809  298512             cookies by design   cookies on a stick       29   

       contributor_id  submitted  n_steps  \
index                                       
0                4470 2004-02-23        4   
1              173674 2004-12-30        8   
2              118163 2004-07-20        4   
3             1848091 2011-04-11       12   
4               50969 2008-05-30        6   
...               ...        ...      ...   
18805           89831 2003-10-24       14   
18806          485109 2010-03-04        5   
18807          226863 2011-09-20       14   
18808          200862 2007-11-25       16   
18809          506822 2008-04-15        9   

                                             description  n_ingredients  \
index                                                                     
0      i think a fondue is a very romantic casual din...             12   
1      this is a very versatile and widely enjoyed pa...             12   
2                 you just have to try it to believe it.              3   
3      this is the recipe that we use at my school ca...             11   
4      since there are already 411 recipes for brocco...              9   
...                                                  ...            ...   
18805         this has been a long time family favorite!              8   
18806  this is a favourite winter warmer. by british ...              9   
18807     this soup is a hearty meal!  from luisa musso.             17   
18808  this is based on a french recipe but i changed...             10   
18809  i've heard of the 'cookies by design' company,...             10   

       n_tags                                               tags  \
index                                                              
0          19  30-minutes-or-less; time-to-make; course; main...   
1          13  30-minutes-or-less; time-to-make; course; main...   
2          30  15-minutes-or-less; time-to-make; course; main...   
3           9  60-minutes-or-less; time-to-make; cuisine; pre...   
4          10  60-minutes-or-less; time-to-make; course; main...   
...       ...                                                ...   
18805      11  60-minutes-or-less; time-to-make; course; prep...   
18806      15  weeknight; 60-minutes-or-less; time-to-make; c...   
18807      28  time-to-make; course; main-ingredient; cuisine...   
18808      18  time-to-make; course; main-ingredient; cuisine...   
18809      12  30-minutes-or-less; time-to-make; course; prep...   

                                             ingredients  
index                                                     
0      beef steaks*vegetable oil*spicy mustard*fresh ...  
1      vegetable oil*vermicelli*rice vinegar*reduced ...  
2                         white bread*mayonnaise*bananas  
3      eggs*margarine*brown sugar*salt*white sugar*va...  
4      milk*garlic powder*salt*frozen broccoli cuts*c...  
...                                                  ...  
18805  eggs*butter*cheddar cheese*sour cream*flour*br...  
18806  potatoes*onions*garlic c

In [14]:
# Оставьте в таблице с рецептами следующие столбцы: id, name, minutes, submitted, description, n_ingredients

recipes_sample_wt.drop(["contributor_id", "n_steps","n_tags","tags","ingredients"], axis=1, inplace=True)
recipes_sample_wt

id                                               name  minutes  \
index                                                                       
0       84797           love is in the air  beef fondue   sauces       25   
1      107229                               open sesame  noodles       28   
2       95926                         say what   banana sandwich        5   
3      453467                 1 in canada chocolate chip cookies       45   
4      306168                             412 broccoli casserole       40   
...       ...                                                ...      ...   
18805   74023                         zucchini cheddar casserole       50   
18806  415406  zucchini  courgette soup  good for weight watc...       45   
18807  464576                                     zuppa by luisa       70   
18808  267661       zurie s holey rustic olive and cheddar bread       80   
18809  298512             cookies by design   cookies on a stick       29   

       submitted                                        description  \
index                                                                 
0     2004-02-23  i think a fondue is a very romantic casual din...   
1     2004-12-30  this is a very versatile and widely enjoyed pa...   
2     2004-07-20             you just have to try it to believe it.   
3     2011-04-11  this is the recipe that we use at my school ca...   
4     2008-05-30  since there are already 411 recipes for brocco...   
...          ...                                                ...   
18805 2003-10-24         this has been a long time family favorite!   
18806 2010-03-04  this is a favourite winter warmer. by british ...   
18807 2011-09-20     this soup is a hearty meal!  from luisa musso.   
18808 2007-11-25  this is based on a french recipe but i changed...   
18809 2008-04-15  i've heard of the 'cookies by design' company,...   

       n_ingredients  
index                 
0                 12  
1                 12  
2                  3  
3                 11  
4                  9  
...              ...  
18805              8  
18806              9  
18807             17  
18808             10  
18809             10  

[18810 rows x 6 columns]

2. Случайным образом выберите 5% строк из каждой таблицы и сохраните две таблицы на разные листы в один файл `recipes.xlsx`. Дайте листам названия "Рецепты" и "Отзывы", соответствующие содержанию таблиц. 

In [15]:
name = "recipes.xlsx"
koef = 0.05
writer = pd.ExcelWriter(name)
new_recipes = recipes_sample_wt.sample(frac = koef) # frac = Fraction. Доля возвращаемых элементов оси
new_recipes.to_excel(writer, sheet_name='Рецепты')

In [16]:
new_reviews = reviews_sample.sample(frac = koef)
new_reviews.to_excel(writer, sheet_name='Отзывы') 
writer.save()

3. Используя `xlwings`, добавьте на лист `Рецепты` столбец `seconds_assign`, показывающий время выполнения рецепта в секундах. Выполните задание при помощи присваивания массива значений диапазону ячеек.

In [17]:
wb = xw.Book(name)
sheet = wb.sheets["Рецепты"]
sheet.range("H1").value = "seconds_assign"
sheet.range("H1").api.font_object.font_style.set('bold')
sheet.range("H2:H1501").options(transpose=True).value = (new_recipes["minutes"] * 60).to_numpy()

4. Используя `xlwings`, добавьте на лист `Рецепты` столбец `seconds_formula`, показывающий время выполнения рецепта в секундах. Выполните задание при помощи формул Excel.

In [18]:
sheet.range("I1").value = "seconds_formula"
sheet.range("I1").api.font_object.font_style.set('bold')
sheet.range("I2").formula = "=D2*60"
sheet.range("I2").api.autofill(type=AutoFillType.xlFillDefault, destination=sheet.range("I2:I1501").api)

5. Добавьте на лист `Рецепты`  столбец `n_reviews`, содержащий кол-во отзывов для этого рецепта. Выполните задание при помощи формул Excel.

In [19]:
sheet.range("J1").value = "n_reviews"
sheet.range("J1").api.font_object.font_style.set('bold')

n = str(len(new_reviews)+1)
sheet.range("J2").formula = f'=COUNTIF(Отзывы!$C$2:$C${n}, "="&B2)'
sheet.range('J2').api.autofill(type=AutoFillType.xlFillDefault, destination=sheet.range("J2:J1501").api)

6. Сделайте названия всех добавленных столбцов полужирными и выровняйте по центру ячейки.

In [20]:
sheet['H1:J1'].api.horizontalalignment = xw.constants.HAlign.xlHAlignCenter

table = xw.Range("A1:I1501")
table.columns[1].column_width = 50
for i in range(4, 9):
    table.columns[i].column_width = 25

7. Раскрасьте ячейки столбца `minutes` в соответствии со следующим правилом: если рецепт выполняется быстрее 5 минут, то цвет - зеленый; от 5 до 10 минут - жёлтый; и больше 10 - красный.

In [21]:
from enum import Enum

class Colors(Enum):
    GREEN = (0, 255, 0)
    YELLOW = (255, 255, 0) 
    RED = (255, 0, 0)

In [ ]:
sheet = wb.sheets['Рецепты']
values = sheet.range("D2:D1501").value

for i in range(len(values)):
    
    if values[i] < 5:
        sheet.range(f"D{i+2}").color = Colors.GREEN.value
    
    elif 5 < values[i] <= 10:
        sheet.range(f"D{i+2}").color = Colors.YELLOW.value
    
    else:
        sheet.range(f"D{i+2}").color =  Colors.RED.value

8. Напишите функцию `validate()`, которая проверяет соответствие всех строк из листа `Отзывы` следующим правилам:
    * Рейтинг - это число от 0 до 5 включительно
    * Соответствующий рецепт имеется на листе `Рецепты`
    
В случае несоответствия этим правилам, выделите строку красным цветом

In [ ]:
sheet = wb.sheets['Отзывы']
def validate(sheet):
    sheet.range('G2').formula ='=COUNTIF(Рецепты!$B$2:$B$1501,"="&C2)>0'
    sheet.range('G2').api.autofill(destination = sheet.range('G2:G6336').api,type = AutoFillType.xlFillDefault)
    for i in range(2,len(reviews_sample)+1):
        rating = sheet.range(f'E{i}').value
        if rating not in range(0,6) or sheet.range(f'G{i}').value==False:
            sheet.range(f'A{i}:E{i}').color = (255,0,0)
    sheet.range('G:G').value = " "
validate(sheet)