In [1]:
import numpy as np

вводим два массива со значениями

In [2]:
# данные из методички
x = np.arange(1,16)
string = '7 12 11 16 17 15 19 18 20 19 21 23 21 23 22'
y = np.array(list(map(int, string.split(' '))))

In [3]:
y

array([ 7, 12, 11, 16, 17, 15, 19, 18, 20, 19, 21, 23, 21, 23, 22])

In [4]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

посчитаем все необходимые переменные 

_x^2_, _x^3_, _x^4_, _x*y_, _x^2*y_, _n (кол-во значений)_

In [6]:
x_2 = np.power(x, 2) # x^2
x_3 = np.power(x, 3) # x^3
x_4 = np.power(x, 4) # x^4

x_y = np.dot(x, y) # x*y
x_2_y = np.dot(x_2, y) # x^2*y

n = x.shape[0]

Урванение зависимости Y от X: 
y = a*x^2 +b*x + c + e_ — это парная квадратичная регрессия.

Для того, чтобы найти переменные (a, b, c) используем метод наименьших квадратов.

Получим систему алгебраических уравнений вида:

a*sum(x^4) + b*sum(x^3) + c*sum(x^2) = sum(x^2*y)  
a*sum(x^3) + b*sum(x^4) + c*sum(x) = sum(x*y)  
a*sum(x^2) + b*sum(x) + c*n = sum(y)  
  
   
Сформируем матрицу A системы, состоящую из коэффициентов при
неизвестных в левых частях уравнений.

In [7]:
A = np.array([[x_4.sum(), x_3.sum(), x_2.sum()], 
              [x_3.sum(), x_2.sum(), x.sum()], 
              [x_2.sum(), x.sum(), n]])
A

array([[178312,  14400,   1240],
       [ 14400,   1240,    120],
       [  1240,    120,     15]])

Применим **метод Крамера** и найдем **уравнение парной квадратичной регрессии**:

In [10]:
yk = np.array([x_2_y.sum(), x_y.sum(), y.sum()])
print(yk)
A1, A2, A3 = A.copy(), A.copy(), A.copy()

D = np.linalg.det(A)
dets = []
for i in range(A.shape[1]):
    A_extra = A.copy()
    A_extra[:, i] = yk
    dets.append(np.linalg.det(A_extra)/D)

a, b, c = dets[0], dets[1], dets[2]

print(f'y = {a:.3f}x^2 + {b:.3f}x + {c:.3f} + e')

[25838  2382   264]
y = -0.074x^2 + 2.151x + 6.523 + e


Найдем **индекс корреляции** _ro = sqrt(1 - (sum(yi-y_)^2 _/(sum(yi-y.mean)^2))_   
и **индекс детерминации** _r_2 _= ro^2_

In [11]:
y_ = a * x * x + b * x + c

# индекс корреляции
ro = np.sqrt(1 - np.power((y - y_),2).sum()/np.power((y - y.mean()),2).sum())

# индекс детерминации
r_2 = np.power(ro, 2)

In [12]:
print(f'индекс корреляции: {ro:.3f}\nиндекс детерминации: {r_2:.3f}')

индекс корреляции: 0.959
индекс детерминации: 0.920


Коэффициент корреляции показывает, есть ли тесная взаимосвязь меду двумя параметрами. 
Т.к полученный коэффициент корреляции близок к 1, значит связь есть, и прогноз довольно точен.   

Коэффициент детерминации близок к 1, что свидетельствует о высоком качестве
подгонки.

Найдем также среднюю относительную ошибку

In [13]:
error = np.abs((y - y_)/y).mean() * 100
print(f'средняя ошибка аппроксимации: {error:.2f}%')

средняя ошибка аппроксимации: 7.79%


Полученный результат находится в пределах допустимых значений ошибки <8…10%. Значит вычисления достаточно точны.